version: "3.1"

services: 
  api:
    image: node
    container_name: faztapi
    build: .
    ports: 
      - "3000:3000"
    volumes: 
      - .:/usr/src/app
    links: 
      - mongo 
  mongo:
    container_name: mydatabase
    image: mongo
    command: mongod
    volumes:
      - /data/db
    ports: 
      - "27017:27017"