version: '3.1'

services:
  api:
    image: node
    container_name: faztapi
    depends_on:
      - mongo
      - redis
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongo
      - redis
    environment:
      - MONGODB_URI=mongodb://mongo/faztdb
      - REDIS_URI=redis://redis:6379
  mongo:
    container_name: mydatabase
    image: mongo
    command: mongod
    volumes:
      - /data/db
    ports:
      - '27017:27017'
    logging:
      driver: none
  redis:
    container_name: fazt-redis
    image: redis
    ports:
      - '6379:6379'
    expose:
      - 6379
    logging:
      driver: none
